for test

diff --git a/.github/workflows/checkARMVMSize.yml b/.github/workflows/checkARMVMSize.yml
--- a/.github/workflows/checkARMVMSize.yml
+++ b/.github/workflows/checkARMVMSize.yml
@@ -16,11 +16,16 @@ jobs:
     if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.repository_owner == 'azure-javaee')
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout oracle/weblogic-azure:main
+    # - name: Checkout oracle/weblogic-azure:main
+    #   uses: actions/checkout@v2
+    #   with:
+    #     repository: oracle/${{ env.repoName }}
+    #     ref: main
+    #     path: ${{ env.repoName }}
+
+    - name: checkout
       uses: actions/checkout@v2
       with:
-        repository: oracle/${{ env.repoName }}
-        ref: main
         path: ${{ env.repoName }}
 
     - uses: azure/login@v1
@@ -33,8 +38,7 @@ jobs:
       run: |
         ls -l ${{ env.repoName }}
         # Path to the properties file
-        property_file="${{ env.repoName }}/resources/azure-common.properties"
-        echo test1
+        property_file="${{ env.repoName }}/resources/azure-common.properties"        
 
         # Check if the properties file exists
         if [ ! -f "$property_file" ]; then
@@ -42,40 +46,43 @@ jobs:
             exit 1
         fi
 
-        echo test2
+        if ! grep -q '^azure\.armBased\.vmSize\.list=' "$property_file"; then
+            echo "Line 'azure.armBased.vmSize.list' not found in $property_file."
+            echo "vm_sizes_changed=false" >> "$GITHUB_OUTPUT"
+            exit 0
+        fi
 
         # Using grep to find the line containing azure.armBased.vmSize.list
-        # Then using sed to extract the value between the double quotes
         vm_size_variable=$(grep '^azure\.armBased\.vmSize\.list=' "$property_file")
-        echo test3
         vm_size_list=${vm_size_variable#*=}
-        vm_size_list=${vm_size_list#*=}
-        echo test4
 
         # Print the extracted value
         echo "$vm_size_list"
 
-        current_sizes="[${vm_size_list}]"
-
         latest_locations=$(az account list-locations --query '[].name' -o tsv)
 
         new_sizes=""
-        echo "{vm_sizes_changed}={false}" >> "$GITHUB_OUTPUT"
-
         for location in $latest_locations; do
-          latest_sizes=$(az vm list-sizes --location $location -o tsv | jq '.[] | select(.name | contains("p")) | .name' | sort | tr '\n' ')
+          latest_sizes=$(az vm list-sizes --location $location | jq '.[] | select(.name | contains("p")) | .name' | tr -d "\"")
           for size in $latest_sizes; do
-            // if new_sizes does not contain size
-            if [[ $(echo "[$new_sizes]" | jq '. | index(${size})') != null ]]; then
-                new_sizes="$new_sizes,\"$size\""
-            fi
-
-            if [[ $(echo "[$current_sizes]" | jq '. | index(${size})') != null ]]; then
-                echo "Changes detected in ARM VM sizes."
-                echo "{vm_sizes_changed}={true}" >> "$GITHUB_OUTPUT"
-            fi            
+            # if new_sizes does not contain size
+            if [[ $(echo "[$new_sizes]" | jq '. | index("'${size}'")') == null ]]; then
+                echo "Add size: ${size}"
+                if [ -z "$new_sizes" ]; then
+                    new_sizes="\"$size\""
+                else
+                    new_sizes="$new_sizes,\"$size\""
+                fi
+            fi       
           done
         done
+
+        if [ ${#new_sizes} -ne ${#vm_size_list} ]; then
+            echo "VM sizes changed"
+            echo "vm_sizes_changed=true" >> "$GITHUB_OUTPUT"
+        else
+            echo "vm_sizes_changed=false" >> "$GITHUB_OUTPUT"
+        fi
 
         echo "Current sizes : $new_sizes"
         echo "{latest_sizes}=\"{new_sizes}\"" >> "$GITHUB_OUTPUT"
