use `az vm run-command create` to execute test script.

diff --git a/.github/workflows/testWlsVmAdmin.yml b/.github/workflows/testWlsVmAdmin.yml
--- a/.github/workflows/testWlsVmAdmin.yml
+++ b/.github/workflows/testWlsVmAdmin.yml
@@ -292,122 +292,42 @@ jobs:
               --query "properties.outputs.adminVMName.value" -o tsv)
             echo "adminVMName=${adminVMName}" >> $GITHUB_ENV
 
-      - name: Verify Network Security Group
-        id: verify-nsg
-        run: |
-            echo "query nsg name, will exit with error if nsg does not exist."
-            export nsgName=$(az network nsg list -g $resourceGroup --query [0].name -o tsv)
-            if [ -z $nsgName ]; then
-              echo "Network Security Group does not exist."
-              exit 1
-            fi
-            echo "nsgName=${nsgName}" >> $GITHUB_ENV
-
-      - name: Get IP of build machine
-        id: get-ip-address
-        run: |
-          myIP=$(dig @ns1.google.com TXT o-o.myaddr.l.google.com +short | tr -d "\"")
-          echo "myIP=${myIP}" >> $GITHUB_ENV
-
-      - name: Add ip address to security rule to access the wls machine
-        id: add-ip-to-security-rule
-        run: |
-            echo "query existing source address prefixes"
-              attempt=0
-              toCreateRule101=false
-              while [[ -z `az network nsg show -g $resourceGroup -n ${nsgName} | grep "NRMS-Rule-101"` && $attempt -le 5 ]]
-              do
-                if [ $attempt -eq 5 ]; then
-                  toCreateRule101=true
-                fi
-                echo "network security group rule NRMS-Rule-101 is not ready"
-                sleep 1m
-                attempt=$((attempt + 1))
-              done
-              if [ $toCreateRule101 == true ]; then
-                az network nsg rule create --name NRMS-Rule-101 \
-                             --nsg-name ${nsgName} \
-                             --priority 101 \
-                             --resource-group $resourceGroup \
-                             --access Allow \
-                             --destination-address-prefixes "*" \
-                             --destination-port-ranges 22 43 \
-                             --direction Inbound \
-                             --protocol Tcp \
-                             --source-address-prefixes $myIP
-              else
-                sourceAddressPrefixes=$(az network nsg rule show \
-                  --resource-group $resourceGroup \
-                  --nsg-name ${nsgName} \
-                  --name NRMS-Rule-101 \
-                  --query "sourceAddressPrefixes")
-                echo "IP of this machine: " ${myIP}
-                sourceAddressPrefixes=$(echo ${myIP} ${sourceAddressPrefixes} | \
-                  sed 's/,/ /g; s/\[//g; s/\]//g; s/"//g')
-                echo ${sourceAddressPrefixes}
-                az network nsg rule update \
-                  --resource-group $resourceGroup \
-                  --nsg-name ${nsgName} \
-                  --name NRMS-Rule-101 \
-                  --source-address-prefixes $sourceAddressPrefixes \
-                  --destination-port-ranges 443 22
-              fi
-
-              echo "Allow access to ${adminConsolePort}"
-              az network nsg rule update \
-                --resource-group $resourceGroup \
-                --nsg-name ${nsgName} \
-                --name WebLogicAdminChannelPort \
-                --access Allow \
-                --source-address-prefixes 10.0.0.0/24
-
-      - name: Restart wls VM
-        id: restart-wls-wm
-        run: |
-            echo "restart vm to make sure security rule work."
-            az vm restart --force --no-wait -g $resourceGroup -n $adminVMName
-            echo "Wait for few minutes to restart"
-            sleep 3m
-
-      - name: Query public IP of AdminServer VM
-        id: query-wls-admin-ip
-        run: |
-            echo "query public ip"
-            publicIP=$(az vm show \
-              --resource-group $resourceGroup \
-              --name $adminVMName -d \
-              --query publicIps -o tsv)
-            echo "##[set-output name=publicIP;]${publicIP}"
-      - name: Create environment variable for AdminServer IP
-        id: env-admin-ip
-        run: echo "wlsPublicIP=${{steps.query-wls-admin-ip.outputs.publicIP}}" >> $GITHUB_ENV
-
       - name: Verify WebLogic Server Installation
         id: verify-wls
         run: |
-          echo "pubilc IP of wls machine: ${wlsPublicIP}"
           echo "Verifying Weblgic server installation"
-          timeout 6m sh -c 'until nc -zv $0 $1; do echo "nc rc: $?"; sleep 5; done' ${wlsPublicIP} 22
-          echo install sshpass
           sudo apt-get install -y sshpass
-          sshpass -p ${wlsPassword} -v ssh -p 22 -o StrictHostKeyChecking=no -o TCPKeepAlive=yes -o ServerAliveCountMax=20 -o ServerAliveInterval=15 -o ConnectTimeout=100 -v -tt weblogic@${wlsPublicIP} 'bash -s' < ${adminOfferPath}/test/scripts/verify-wls-path.sh
+          local scriptPath=https://raw.githubusercontent.com/${repoPath}/${testbranchName}/weblogic-azure-vm/arm-oraclelinux-wls-admin/test/scripts/verify-wls-path.sh
+          local provisioningState=$(az vm run-command create --name "VerifyWebLogicHome" \
+            --resource-group $resourceGroup \
+            --vm-name $adminVMName \
+            --run-as-user root \
+            --timeout-in-seconds 3600 \
+            --script-uri ${scriptPath} \
+            --query provisioningState)
 
-      - name: Restart remote SSH agent
-        id: restart-remote-ssh
-        run: |
-            echo "Restart remote SSH agent"
-            az vm user reset-ssh \
-              --resource-group $resourceGroup \
-              --name ${{ env.adminVMName }}
-            sleep 1m             
+          if [ "$provisioningState" != "Succeeded" ]; then
+            echo "WebLogic Server installation failed"
+            exit 1
+          fi
 
       - name: Verify system services at admin server
         id: veriy-admin-service
         run: |
-          echo "wait for 22 port"
-          timeout 6m sh -c 'until nc -zv $0 $1; do echo "nc rc: $?"; sleep 5; done' ${wlsPublicIP} 22
           echo "Verifying WebLogic services at admin server"
-          sshpass -p ${wlsPassword} -v ssh -p 22 -o StrictHostKeyChecking=no -o TCPKeepAlive=yes -o ServerAliveCountMax=20 -o ServerAliveInterval=15 -o ConnectTimeout=100 -v -tt weblogic@${wlsPublicIP} 'bash -s' < ${{ env.adminOfferPath }}/test/scripts/verify-services.sh
+          local scriptPath=https://raw.githubusercontent.com/${repoPath}/${testbranchName}/weblogic-azure-vm/arm-oraclelinux-wls-admin/test/scripts/verify-services.sh
+          local provisioningState=$(az vm run-command create --name "VerifyWebLogicServices" \
+            --resource-group $resourceGroup \
+            --vm-name $adminVMName \
+            --run-as-user root \
+            --timeout-in-seconds 3600 \
+            --script-uri ${scriptPath} \
+            --query provisioningState)
+
+          if [ "$provisioningState" != "Succeeded" ]; then
+            echo "WebLogic Server services verification failed"
+            exit 1
+          fi
 
       - name: Verify WebLogic Server Access
         id: verify-wls-access
