Add 'none' option for database type and improve parameter file handling

diff --git a/.github/workflows/testWlsVmAdmin.yml b/.github/workflows/testWlsVmAdmin.yml
--- a/.github/workflows/testWlsVmAdmin.yml
+++ b/.github/workflows/testWlsVmAdmin.yml
@@ -16,6 +16,7 @@ on:
         default: 'mssqlserver'
         type: choice
         options:
+          - none
           - mssqlserver
           - mssqlserver-passwordless
           - postgresql(flexible)
@@ -289,8 +290,16 @@ jobs:
               
               ## generate parameter file 
               echo 'current working directory: $(pwd)'
-              parameter_template='./${{ env.adminOfferPath }}/src/test/scripts/parameters-deploy-template.json'
-              parameter_output='./${{ env.adminOfferPath }}/src/test/parameters-deploy-${{ github.job }}.json'
+              # check if file exists
+              if [ ! -f '${{ env.adminOfferPath }}/src/test/scripts/parameters-deploy-template.json' ]; then
+                  echo 'Error: parameters-deploy-template.json not found!'
+                  # the whole file path is 
+                  echo '${{ env.adminOfferPath }}/src/test/scripts/parameters-deploy-template.json'
+                  exit 1
+              fi
+              parameter_template='${{ env.adminOfferPath }}/src/test/scripts/parameters-deploy-template.json'
+              echo 'Define the output parameter file path'
+              parameter_output='${{ env.adminOfferPath }}/src/test/parameters-deploy-${{ github.job }}.json'
               envsubst < '$parameter_template' > '$parameter_output' 
               
               # Accept Image Terms
